### ISSUE TITLE
Cannot add some URL's in an organization's note

### ISSUE THREAD

**Issue by bruhnild** [zammad/zammad-user-documentation#136]
I would like to add URL's redirecting to our gitlab projects in some organizations's note (clients) but for some reasons I cannot paste some URL's...

Example : https://gitlab.makina-corpus.net/Produits/geotrek/clients/pn-vanoise

![Peek 27-07-2023 13-13](https://github.com/zammad/zammad-user-documentation/assets/26433045/005e164d-8e6c-4729-a06e-8f5ff8c05ecb)

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
